# Inherit environment
set -g default-command "/bin/bash --login"

# Set true color support
set-option -sa terminal-overrides ",xterm*:Tc"

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Tmux Vim Navigator
set -g @plugin 'christoomey/vim-tmux-navigator'

# Yank
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @override_copy_command 'xclip -selection clipboard'
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Open new windows in current directory
bind-key c new-window -c "#{pane_current_path}"

# Tmux Sessionizer
bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"

# Colorscheme
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'

run '~/.tmux/plugins/tpm/tpm'
